name: Build, Push Docker Image, and Update Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository triggering the action
        uses: actions/checkout@v2  # Checkout the repository that triggered the action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push Docker image with commit hash
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      #   run: |
      #     IMAGE_TAG=${GITHUB_SHA}
      #     cd frontend
      #     docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout Kubernetes Manifests Repo
        uses: actions/checkout@v2
        with:
          repository: gautamlakhani2507/k8s-manifests
          token: ${{ secrets.ERSONAL_ACCESS_TOKEN }}
          path: manifests # This creates the folder on the runner

      - name: List files for debugging
        run: |
          ls -R /home/runner/work/custom-fe-be/custom-fe-be
    


      - name: Update image tag in Kubernetes manifests repository
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.ERSONAL_ACCESS_TOKEN }}
          repository: 'gautamlakhani2507/k8s-manifests'
          targetBranch: main
          commitChange: false 
          workDir: manifests
          changes: |
            {
              "k8s-manifests/deployment.yaml": {
              "spec.template.spec.containers.image": "218306567362.dkr.ecr.us-east-1.amazonaws.com/practice-repo:${{ github.sha }}"
    
              }
                } 

      - name: Show diff and last commit
        run: |
          cd manifests
          git status
          git diff
          git log -n 2          
      - name: Commit and push updated manifest
        run: |
         cd manifests
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git config user.name "github-actions[bot]"
         git add .
         git diff --cached --quiet || git commit -m "Update deployment image to commit $GITHUB_SHA"
         git push origin main

   

  
