name: Build, Push Docker Image, and Update Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository triggering the action
        uses: actions/checkout@v2  # Checkout the repository that triggered the action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push Docker image with commit hash
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      #   run: |
      #     IMAGE_TAG=${GITHUB_SHA}
      #     cd frontend
      #     docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout Kubernetes Manifests Repo
        uses: actions/checkout@v2
        with:
          repository: gautamlakhani2507/k8s-manifests
          token: ${{ secrets.ERSONAL_ACCESS_TOKEN }}
          path: k8s-manifests  # This creates the folder on the runner

      - name: List files for debugging
        run: |
          ls -R /home/runner/work/custom-fe-be/custom-fe-be
    


      - name: Update image tag in Kubernetes manifests repository
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.ERSONAL_ACCESS_TOKEN }}
          repository: 'gautamlakhani2507/k8s-manifests'
          targetBranch: main
          commitChange: true 
          workDir: k8s-manifests
          changes: |
            {
              "deployment.yaml": {
                "spec.template.spec.containers.image": "${GITHUB_SHA}"
              }
            }
